### PR TITLE
Example for an Encoder and Decoder using the DynamicValue API

### PR DESCRIPTION
**Pull request by calvinlfer**
- Add scalafmt
- Update zio-schema to 0.1.2

### CODE REVIEW

**Comment by domdorn** [comment]
Example7 is marked as deleted.. its probably just reformated using scalafmt, right?

**Comment by calvinlfer** [comment]
I renamed exercise to example that’s why, just got moved around

**Comment by domdorn** [comment]
> I renamed exercise to example that’s why, just got moved around

could u please use `git mv` for that? that way the history is kept (which is important in this case as I've made many commits for every part of johns talk and people can follow the various steps that way.

**Comment by calvinlfer** [comment]
I `git mv`d it but GitHub seems to disagree 😆

**Comment by domdorn** [comment]
> I `git mv`d it but GitHub seems to disagree 😆

hmm.. could u maybe just take it out from the PR (= leave it like it was)?

**Comment by calvinlfer** [comment]
Donezo

**Comment by domdorn** [comment]
<3 @calvinlfer  if we ever meet, I'll own you a 🍺 :)

**Pull request merged**
